version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: zapulse
      POSTGRES_PASSWORD: zapulse_pwd
      POSTGRES_DB: zapulse_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5430"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zapulse"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
